name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: Dlogunoff
          base: header, repositories
          plugin_introduction: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_limit: 4
          plugin_lines: yes
          plugin_gists: yes
#           plugin_wakatime: yes
#           plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
#           plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
